### ISSUE TITLE
Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/build.make:62: recipe for target 'Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/pga460.cpp.o' failed make[2]: *** [Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/pga460.cpp.o] Error 1 CMakeFiles/Makefile2:7339: recipe for target 'Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/all' failed

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#276]

**Comment by Jaeyoung-Lim** [comment]
@lioneleeedadad What is the question? I don't see anything in the description

**Comment by lioneleeedadad** [comment]
I can't do catkin_make .. and this error is appearing

**Comment by lioneleeedadad** [comment]
there is an error in Firmware !

**Comment by Jaeyoung-Lim** [comment]
If you are doing catkin_make you clearly are not following the setup process on the readme of this repo.

Could you try following the readme?

In order for me to help, you need to "describe" your problem in the description. as detailed as possible- what you are trying to do, how you tried and what is not working.

**Comment by lioneleeedadad** [comment]
I followed the setup process how I now cloned the rqt reconfigure and other packages related to rqt and then I'm trying to do that catkin_make and I'm recieving output 
cc1plus: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/build.make:62: recipe for target 'Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/pga460.cpp.o' failed
make[2]: *** [Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/pga460.cpp.o] Error 1
CMakeFiles/Makefile2:10238: recipe for target 'Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/all' failed
make[1]: *** [Firmware/src/drivers/distance_sensor/pga460/CMakeFiles/drivers__pga460.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by lioneleeedadad** [comment]
Also this issue is related to PX4 avoidance package thats why I'm asking here .. So please help me :)

**Comment by Jaeyoung-Lim** [comment]
This is much more clear.

So to make this clear. This is not an issue with the avoidane package itself, but a problem with your installation.

I see a few problems from your log:
- where is your firmware located? It shouldn't be in the `catkin_ws` Please follow the installation instructions precisely on the devguide: http://dev.px4.io/en/setup/dev_env_linux.html
- You shouldn't be using `catkin_make` as the avoidance package builds on `catkin build` You cannot use both in the same workspace. You need to clean the workspace before you do any builds
- I am curious if you were able to run any ros node with your system? If not, to verify everything is fine try following one of the ROS examples so that at least you are sure everything is alright with ROS-and rqt reconfigure

**Comment by lioneleeedadad** [comment]
My Firmware is in catkin_ws/src/

**Comment by Jaeyoung-Lim** [comment]
@lioneleeedadad Exactly in shouldn't be there

**Comment by lioneleeedadad** [comment]
I will try to add it in its right place and tell you what happened

**Comment by mhkabir** [comment]
@lioneleeedadad Please use discuss.px4.io for help instead of opening new issues. We will close and lock issues which do not include information and do not follow standard guidelines.
