### ISSUE TITLE
About camera FOV

### ISSUE THREAD

**Issue by darshanz** [PX4/avoidance#556]
Just noticed the value for _vertical_FOV_range_sensor_  is set to be _20.0._ in  in _planner_functions.cpp_ .

I am not sure if this is camera dependent value as it is hardcoded. The Realsense camera mentioned in the paper seems to have a vertical FOV of 46 degrees.
Or is it an arbitrarily chosen value for considering safe margins.

**Comment by jkflying** [comment]
This is the value used for the collision prevention, which is only 2D-aware. It takes a horizontal 20 degree slice and sends it to the flight controller, so that it can be used to restrict manual control.

If you have a much larger angle it ends up being impossible to fly over things without a very high clearance.

**Comment by darshanz** [comment]
Thank you.
